### ISSUE TITLE
哈哈，你好，发现你是同胞

### ISSUE THREAD

**Issue by xiaoxiaoliya** [icespite/FridaHooker#2]
首先感谢你的伟大工作，我下载了你的3.0.1版本在安装frida server的时候，我找不到我的手机文件目录，就只能看到一个最近的文档目录，从而找不到我复制进去的frida包，我将它换成3.0.0版本，我成功安装了

**Comment by icespite** [comment]
你在文件管理系统左侧应该能找到设备文件夹，一层层点进你保存的路径应该就可以啦。
